apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: ps2
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: ps2
    name: ps2
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: ps2:latest
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      git:
        uri: https://github.com/dwojciec/ps.git
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: jboss-webserver30-tomcat8-openshift:latest
          namespace: openshift
      type: Source
    triggers:
    - github:
        secret: StdHu9iG_dB82LB3b04E
      type: GitHub
    - generic:
        secret: DuQDzbg9UwKciLf-pwIl
      type: Generic
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
  status:
    lastVersion: 0
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    generation: 2
    labels:
      app: ps2
    name: ps2
  spec:
    replicas: 1
    selector:
      app: ps2
      deploymentconfig: ps2
    strategy:
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        annotations:
          openshift.io/container.ps2.image.entrypoint: '["/opt/webserver/bin/launch.sh"]'
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          app: ps2
          deploymentconfig: ps2
      spec:
        containers:
        - image: 172.30.199.108:5000/stefit/ps2@sha256:ccc10b35f17d602021367e646920e6c79f957faa55430350a666c12657fb23de
          imagePullPolicy: Always
          name: ps2
          ports:
          - containerPort: 8443
            protocol: TCP
          - containerPort: 8778
            protocol: TCP
          - containerPort: 8080
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - ps2
        from:
          kind: ImageStreamTag
          name: ps2:latest
          namespace: stefit
      type: ImageChange
  status:
    availableReplicas: 1
    observedGeneration: 2
    replicas: 1
    updatedReplicas: 1
